// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const axios = require('axios')

describe('SearchWH1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SearchWH1', async function() {
    await driver.get("https://volunteercentrecounty.org/paid-job-openings")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    
    // Wait for the search input to be visible
    await driver.wait(until.elementLocated(By.css(".md\\3Amt-5")), 10000)
    const searchInput = await driver.findElement(By.css(".md\\3Amt-5"))
    await searchInput.click()
    await searchInput.sendKeys("educator")
    
    // Wait for search results to load
    await driver.sleep(2000)
    
    try {
      // Make API request to get sorted data
      const response = await axios.get('https://api.volunteercentrecounty.org/web-api/paid-job', {
        params: {
          search: 'educator',
          limit: 15,
          offset: 0,
          order: 'DESC',
          orderBy: 'lastRefreshed'
        },
        headers: {
          'Accept': 'application/json, text/plain, */*',
          'Origin': 'https://volunteercentrecounty.org',
          'Referer': 'https://volunteercentrecounty.org/'
        }
      })

      const jobs = response.data.data
      console.log(`API returned ${jobs.length} jobs`)
      
      const educatorItems = []

      // Verify sorting and collect items
      for (let i = 0; i < jobs.length; i++) {
        const currentJob = jobs[i]
        if (currentJob.title.toLowerCase().includes("educator")) {
          educatorItems.push({
            title: currentJob.title,
            lastRefreshed: currentJob.lastRefreshed
          })
        }
        
        // Verify sorting order
        if (i < jobs.length - 1) {
          const currentDate = new Date(currentJob.lastRefreshed)
          const nextDate = new Date(jobs[i + 1].lastRefreshed)
          assert(currentDate >= nextDate, 
            `Sorting order is incorrect: ${currentJob.title} (${currentJob.lastRefreshed}) should be after ${jobs[i + 1].title} (${jobs[i + 1].lastRefreshed})`)
        }
      }
      
      // Log the results
      console.log(`\nFound ${educatorItems.length} items containing "educator" (sorted by lastRefreshed DESC):`)
      educatorItems.forEach((item, index) => {
        console.log(`${index + 1}. ${item.title} (Last Refreshed: ${item.lastRefreshed})`)
      })
      
      // Assert that we found at least one item
      assert.ok(educatorItems.length > 0, 'No items found containing "educator"')
      
    } catch (error) {
      console.error('API Error:', error.response ? {
        status: error.response.status,
        data: error.response.data,
        headers: error.response.headers
      } : error.message)
      throw error
    }
  })
})
